input {
  beats {
    port => 5044
  }
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => { "[@metadata][target_index]" => "logstash-%{+YYYY.MM.dd}" }
  }
}

output {
  elasticsearch {
    hosts => ["https://127.0.0.1:9200"]
    ssl_certificate_authorities => ["/etc/logstash/http_ca.crt"]
    ssl_enabled => true
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
    index => "%{[@metadata][target_index]}"
  }
}
